# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csensor.proto\"\xa0\x01\n\x06Sensor\x12\x11\n\x04type\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02ip\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04port\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x12\n\x05state\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x18\n\x0btemperature\x18\x05 \x01(\x02H\x04\x88\x01\x01\x42\x07\n\x05_typeB\x05\n\x03_ipB\x07\n\x05_portB\x08\n\x06_stateB\x0e\n\x0c_temperatureb\x06proto3'
)




_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Sensor.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Sensor.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='Sensor.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='Sensor.state', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='Sensor.temperature', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_type', full_name='Sensor._type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_ip', full_name='Sensor._ip',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_port', full_name='Sensor._port',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_state', full_name='Sensor._state',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_temperature', full_name='Sensor._temperature',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=17,
  serialized_end=177,
)

_SENSOR.oneofs_by_name['_type'].fields.append(
  _SENSOR.fields_by_name['type'])
_SENSOR.fields_by_name['type'].containing_oneof = _SENSOR.oneofs_by_name['_type']
_SENSOR.oneofs_by_name['_ip'].fields.append(
  _SENSOR.fields_by_name['ip'])
_SENSOR.fields_by_name['ip'].containing_oneof = _SENSOR.oneofs_by_name['_ip']
_SENSOR.oneofs_by_name['_port'].fields.append(
  _SENSOR.fields_by_name['port'])
_SENSOR.fields_by_name['port'].containing_oneof = _SENSOR.oneofs_by_name['_port']
_SENSOR.oneofs_by_name['_state'].fields.append(
  _SENSOR.fields_by_name['state'])
_SENSOR.fields_by_name['state'].containing_oneof = _SENSOR.oneofs_by_name['_state']
_SENSOR.oneofs_by_name['_temperature'].fields.append(
  _SENSOR.fields_by_name['temperature'])
_SENSOR.fields_by_name['temperature'].containing_oneof = _SENSOR.oneofs_by_name['_temperature']
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:Sensor)
  })
_sym_db.RegisterMessage(Sensor)


# @@protoc_insertion_point(module_scope)
