# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lampada.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlampada.proto\"\x1f\n\rLampadaStatus\x12\x0e\n\x06ligada\x18\x01 \x01(\x08\"1\n\x0eLampadaControl\x12\r\n\x05ligar\x18\x01 \x01(\x08\x12\x10\n\x08\x64\x65sligar\x18\x02 \x01(\x08\"4\n\x0fLampadaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2k\n\x0eLampadaService\x12+\n\tGetStatus\x12\x0e.LampadaStatus\x1a\x0e.LampadaStatus\x12,\n\x07\x43ontrol\x12\x0f.LampadaControl\x1a\x10.LampadaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lampada_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LAMPADASTATUS']._serialized_start=17
  _globals['_LAMPADASTATUS']._serialized_end=48
  _globals['_LAMPADACONTROL']._serialized_start=50
  _globals['_LAMPADACONTROL']._serialized_end=99
  _globals['_LAMPADARESPONSE']._serialized_start=101
  _globals['_LAMPADARESPONSE']._serialized_end=153
  _globals['_LAMPADASERVICE']._serialized_start=155
  _globals['_LAMPADASERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
