# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoBuff/lampada.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoBuff/lampada.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17protoBuff/lampada.proto\"!\n\x0eLampadaControl\x12\x0f\n\x07\x63ontrol\x18\x01 \x01(\t\"\x19\n\x07Lampada\x12\x0e\n\x06status\x18\x01 \x01(\x08\x62\x06proto3'
)




_LAMPADACONTROL = _descriptor.Descriptor(
  name='LampadaControl',
  full_name='LampadaControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='control', full_name='LampadaControl.control', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=60,
)


_LAMPADA = _descriptor.Descriptor(
  name='Lampada',
  full_name='Lampada',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Lampada.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['LampadaControl'] = _LAMPADACONTROL
DESCRIPTOR.message_types_by_name['Lampada'] = _LAMPADA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LampadaControl = _reflection.GeneratedProtocolMessageType('LampadaControl', (_message.Message,), {
  'DESCRIPTOR' : _LAMPADACONTROL,
  '__module__' : 'protoBuff.lampada_pb2'
  # @@protoc_insertion_point(class_scope:LampadaControl)
  })
_sym_db.RegisterMessage(LampadaControl)

Lampada = _reflection.GeneratedProtocolMessageType('Lampada', (_message.Message,), {
  'DESCRIPTOR' : _LAMPADA,
  '__module__' : 'protoBuff.lampada_pb2'
  # @@protoc_insertion_point(class_scope:Lampada)
  })
_sym_db.RegisterMessage(Lampada)


# @@protoc_insertion_point(module_scope)
