# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoBuff/MulticastMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoBuff/MulticastMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n protoBuff/MulticastMessage.proto\"\\\n\x10MulticastMessage\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x14\n\x07udpport\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\n\n\x08_udpportb\x06proto3'
)




_MULTICASTMESSAGE = _descriptor.Descriptor(
  name='MulticastMessage',
  full_name='MulticastMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='MulticastMessage.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='MulticastMessage.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='MulticastMessage.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='udpport', full_name='MulticastMessage.udpport', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_udpport', full_name='MulticastMessage._udpport',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=36,
  serialized_end=128,
)

_MULTICASTMESSAGE.oneofs_by_name['_udpport'].fields.append(
  _MULTICASTMESSAGE.fields_by_name['udpport'])
_MULTICASTMESSAGE.fields_by_name['udpport'].containing_oneof = _MULTICASTMESSAGE.oneofs_by_name['_udpport']
DESCRIPTOR.message_types_by_name['MulticastMessage'] = _MULTICASTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MulticastMessage = _reflection.GeneratedProtocolMessageType('MulticastMessage', (_message.Message,), {
  'DESCRIPTOR' : _MULTICASTMESSAGE,
  '__module__' : 'protoBuff.MulticastMessage_pb2'
  # @@protoc_insertion_point(class_scope:MulticastMessage)
  })
_sym_db.RegisterMessage(MulticastMessage)


# @@protoc_insertion_point(module_scope)
