/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MulticastMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "MulticastMessage.pb-c.h"
void   multicast_message__init
                     (MulticastMessage         *message)
{
  static const MulticastMessage init_value = MULTICAST_MESSAGE__INIT;
  *message = init_value;
}
size_t multicast_message__get_packed_size
                     (const MulticastMessage *message)
{
  assert(message->base.descriptor == &multicast_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t multicast_message__pack
                     (const MulticastMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &multicast_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t multicast_message__pack_to_buffer
                     (const MulticastMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &multicast_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MulticastMessage *
       multicast_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MulticastMessage *)
     protobuf_c_message_unpack (&multicast_message__descriptor,
                                allocator, len, data);
}
void   multicast_message__free_unpacked
                     (MulticastMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &multicast_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor multicast_message__field_descriptors[2] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MulticastMessage, sender),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MulticastMessage, content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned multicast_message__field_indices_by_name[] = {
  1,   /* field[1] = content */
  0,   /* field[0] = sender */
};
static const ProtobufCIntRange multicast_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor multicast_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MulticastMessage",
  "MulticastMessage",
  "MulticastMessage",
  "",
  sizeof(MulticastMessage),
  2,
  multicast_message__field_descriptors,
  multicast_message__field_indices_by_name,
  1,  multicast_message__number_ranges,
  (ProtobufCMessageInit) multicast_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
