/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MulticastMessage.proto */

#ifndef PROTOBUF_C_MulticastMessage_2eproto__INCLUDED
#define PROTOBUF_C_MulticastMessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MulticastMessage MulticastMessage;


/* --- enums --- */


/* --- messages --- */

struct  _MulticastMessage
{
  ProtobufCMessage base;
  char *sender;
  char *content;
};
#define MULTICAST_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&multicast_message__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* MulticastMessage methods */
void   multicast_message__init
                     (MulticastMessage         *message);
size_t multicast_message__get_packed_size
                     (const MulticastMessage   *message);
size_t multicast_message__pack
                     (const MulticastMessage   *message,
                      uint8_t             *out);
size_t multicast_message__pack_to_buffer
                     (const MulticastMessage   *message,
                      ProtobufCBuffer     *buffer);
MulticastMessage *
       multicast_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   multicast_message__free_unpacked
                     (MulticastMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MulticastMessage_Closure)
                 (const MulticastMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor multicast_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_MulticastMessage_2eproto__INCLUDED */
