# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoBuff/sensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoBuff/sensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protoBuff/sensor.proto\"P\n\x06Sensor\x12\x12\n\x05state\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x18\n\x0btemperature\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x08\n\x06_stateB\x0e\n\x0c_temperature\"1\n\tSensorMsg\x12\x16\n\toperation\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_operationb\x06proto3'
)




_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='Sensor.state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='Sensor.temperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_state', full_name='Sensor._state',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_temperature', full_name='Sensor._temperature',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=26,
  serialized_end=106,
)


_SENSORMSG = _descriptor.Descriptor(
  name='SensorMsg',
  full_name='SensorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='SensorMsg.operation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_operation', full_name='SensorMsg._operation',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=108,
  serialized_end=157,
)

_SENSOR.oneofs_by_name['_state'].fields.append(
  _SENSOR.fields_by_name['state'])
_SENSOR.fields_by_name['state'].containing_oneof = _SENSOR.oneofs_by_name['_state']
_SENSOR.oneofs_by_name['_temperature'].fields.append(
  _SENSOR.fields_by_name['temperature'])
_SENSOR.fields_by_name['temperature'].containing_oneof = _SENSOR.oneofs_by_name['_temperature']
_SENSORMSG.oneofs_by_name['_operation'].fields.append(
  _SENSORMSG.fields_by_name['operation'])
_SENSORMSG.fields_by_name['operation'].containing_oneof = _SENSORMSG.oneofs_by_name['_operation']
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
DESCRIPTOR.message_types_by_name['SensorMsg'] = _SENSORMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR,
  '__module__' : 'protoBuff.sensor_pb2'
  # @@protoc_insertion_point(class_scope:Sensor)
  })
_sym_db.RegisterMessage(Sensor)

SensorMsg = _reflection.GeneratedProtocolMessageType('SensorMsg', (_message.Message,), {
  'DESCRIPTOR' : _SENSORMSG,
  '__module__' : 'protoBuff.sensor_pb2'
  # @@protoc_insertion_point(class_scope:SensorMsg)
  })
_sym_db.RegisterMessage(SensorMsg)


# @@protoc_insertion_point(module_scope)
